export {default as NavBar} from './NavBar'
export {default as Hero} from './Hero'
export {default as Search} from './Search'
export {default as Footer} from './Footer'
export {default as Trending} from './Trending'
export {default as Chart} from './Chart'