export {default as NavBar} from './Header'
export {default as Search} from './Search'
export {Trending} from './Trending'
export {default as ChartsContainer} from './Charts/ChartsContainer'
export {default as ThemeSwitch} from './ThemeSwitch'
export {default as CoinGecko} from './CoinGecko'